package utils.constants

object JsonFieldsManager:
  val RoomName = "name"
  val RoomCells = "cells"
  val RoomLinks = "links"
  val MapName = "name"
  val MapRooms = "rooms"
  val MapInitialRoom = "initialRoom"
  val MapInitialPosition = "initialPosition"
  val SaveMapName = "mapName"
  val SaveMap = "map"
  val SaveRoom = "room"
  val SaveCurrentPosition = "currentPos"
  val SaveStartPosition = "startPos"
  val SaveItems = "items"
  val SaveScore = "score"
  val SaveMiniMap = "minimap"
  val CellType = "cellType"
  val Basic = "BasicCell"
  val Cliff = "CliffCell"
  val ButtonBlock = "ButtonBlockCell"
  val Button = "ButtonCell"
  val CoveredHole = "CoveredHoleCell"
  val Hole = "HoleCell"
  val PressurePlateBlock = "PressurePlateBlockCell"
  val PressurePlate = "PressurePlateCell"
  val Teleport = "TeleportCell"
  val TeleportDestination = "TeleportDestinationCell"
  val Wall = "WallCell"
  val Rock = "RockCell"
  val Plant = "PlantCell"
  val Lock = "LockCell"
